# Generated by Django 2.2.3 on 2019-07-31 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Désignation')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Prix unitaire')),
                ('size', models.CharField(blank=True, max_length=150, null=True, verbose_name='Poids')),
                ('color', models.CharField(max_length=150, null=True, verbose_name='Couleur produit')),
                ('modele', models.CharField(max_length=150, null=True, verbose_name='Modele')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date Creation Article')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom complet')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Adresse Client')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('bio', models.TextField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=10, null=True, verbose_name='sexe')),
                ('sales_revenue_product', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=50, null=True, verbose_name='C-A produits')),
                ('sales_revenue_delivery', models.DecimalField(decimal_places=2, default=0.0, max_digits=50, null=True, verbose_name='C-A livraison')),
                ('first_delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de premiere livraison')),
                ('last_delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de dernière livraison')),
                ('number_deliveries', models.IntegerField(blank=True, default=0, null=True, verbose_name='Nombre de livraison')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date Creation Client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParcelQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, null=True, verbose_name='Nombre de produit')),
                ('id_article', models.IntegerField(blank=True, null=True)),
                ('id_parcel', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'quantities',
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro tracking')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True, verbose_name='Poids colis')),
                ('status', models.CharField(choices=[('Livré', 'Livré'), ('En attente de collecte', 'En attente de collecte'), ('Avec le livreur', 'Avec le livreur'), ('Avec la société de livraison', 'Avec la société de livraison')], default='En attente de collecte', max_length=20, verbose_name='Status colis')),
                ('comment', models.CharField(blank=True, default='vide', max_length=20, null=True, verbose_name='commentaire colis')),
                ('date_delivery', models.DateField(blank=True, null=True, verbose_name='Date livraison colis')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date création colis')),
                ('delivery_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=100, null=True, verbose_name='Prix de livraison')),
                ('articles', models.ManyToManyField(blank=True, to='backend.Article')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Livré', 'Livré'), ('En cours', 'En cours')], max_length=50, null=True, verbose_name='Status livraison')),
                ('delivery_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Numéro livraison')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date Creation Livraison')),
                ('date_livraison', models.DateField(blank=True, null=True, verbose_name='Date Livraison')),
                ('parcel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colis_livraison', to='backend.Parcel')),
            ],
        ),
    ]
