# Generated by Django 2.2.3 on 2019-07-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190731_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date création colis'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='date_delivery',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date livraison colis'),
        ),
    ]
