# Generated by Django 2.2.3 on 2019-07-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20190731_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Poids colis'),
        ),
    ]
