# Generated by Django 2.2.3 on 2019-07-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20190731_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='commentaire',
            field=models.CharField(blank=True, default='rien à signaler', max_length=100, null=True, verbose_name='commentaire tournéé'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='comment',
            field=models.CharField(blank=True, default='vide', max_length=100, null=True, verbose_name='commentaire colis'),
        ),
    ]
