# Generated by Django 2.2.3 on 2019-08-01 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20190731_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='commentaire',
            field=models.CharField(blank=True, default='rien à signaler', max_length=100, null=True, verbose_name='commentaire tournée'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(blank=True, choices=[('Livré', 'Livré'), ('En cours', 'En cours')], default='En cours', max_length=50, null=True, verbose_name='Status livraison'),
        ),
    ]
