# Generated by Django 2.2.3 on 2019-08-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20190801_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='parcel',
        ),
        migrations.AddField(
            model_name='delivery',
            name='parcel',
            field=models.ManyToManyField(blank=True, null=True, to='backend.Parcel'),
        ),
    ]
