# Generated by Django 2.2.3 on 2019-08-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20190801_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='isChecked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
