# Generated by Django 2.2.3 on 2019-08-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_parcel_ischecked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de premiere livraison'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='comment',
            field=models.CharField(blank=True, default='vide', max_length=150, null=True, verbose_name='commentaire colis'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('Livré', 'Livré'), ('En attente de collecte', 'En attente de collecte'), ('Avec le livreur', 'Avec le livreur'), ('Avec la société de livraison', 'Avec la société de livraison')], default='En attente de collecte', max_length=150, verbose_name='Status colis'),
        ),
    ]
