# Generated by Django 2.2.3 on 2019-08-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20190820_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='created_by',
        ),
    ]
